language: bash

before_install:
  - export HOST_USER_ID=`id -g`
  - export PARENT_DIRECTORY=/home/travis/build/vsevolod-skripnik
  - export ROOT_DIRECTORY=${TRAVIS_BUILD_DIR}
  - export MEDIA_DIRECTORY=${TRAVIS_BUILD_DIR}/resources/media
  - export STATIC_DIRECTORY=${TRAVIS_BUILD_DIR}/resources/static
  - export CERTBOT_DIRECTORY=${TRAVIS_BUILD_DIR}/resources/certbot

install:
  - >
    docker-compose \
      -f compose/postgres.yml \
      -f compose/django.yml \
      --project-directory . \
      build

# before_script
# script
# after_success or after_failure

before_deploy:
  - docker save -o vash_django.tar vash_django
  - docker save -o vash_postgres.tar vash_postgres

deploy:
  - echo deploy!

# OPTIONAL after_deploy
# after_script

addons:
  apt:
    packages:
    - sshpass
