language: bash


# Prepare environment and dependencies
before_install:
  - export HOST_USER_ID=`id -u`

  - export PARENT_DIRECTORY=/home/travis/build/vsevolod-skripnik
  - export ROOT_DIRECTORY=${TRAVIS_BUILD_DIR}
  - export MEDIA_DIRECTORY=${TRAVIS_BUILD_DIR}/resources/media
  - export STATIC_DIRECTORY=${TRAVIS_BUILD_DIR}/resources/static
  - export CERTBOT_DIRECTORY=${TRAVIS_BUILD_DIR}/resources/certbot

  - export SSHPASS=${PRODUCTION_SERVER_PASSWORD}
  - alias ssh_to_production='sshpass -e ssh ${PRODUCTION_SERVER_USERNAME}@${PRODUCTION_SERVER_HOST}'
  - shopt -s expand_aliases
  - ssh-keyscan -t rsa ${PRODUCTION_SERVER_HOST} > ~/.ssh/known_hosts

  - export PRODUCTION_USER_ID=(ssh_to_production 'id -u')

# Build
install:
  - echo "${PRODUCTION_USER_ID}awdawd"
  - >
    HOST_USER_ID=${PRODUCTION_USER_ID} docker-compose \
        -f compose/postgres.yml \
        -f compose/django.yml \
        --project-directory . \
        build

# Test
before_script:
  - echo 'Testing goes here'

# Deploy to production
script:
  - docker save -o vash_django.tar vash_django
  -
    >
    sshpass \
      -e scp \
      vash_django.tar \
      ${PRODUCTION_SERVER_USERNAME}@${PRODUCTION_SERVER_DOMAIN}:~/images

# Check if alive
after_script:
  - whoami


addons:
  apt:
    packages:
    - sshpass
