language: bash


addons:
  apt:
    packages:
    - sshpass
    - docker-ce


before_install:
  - export COMMIT=`echo ${TRAVIS_COMMIT:0:7}`  # Shorten commit hash

  # Directories
  - export ROOT_DIRECTORY=${TRAVIS_BUILD_DIR}
  - export MEDIA_DIRECTORY=${TRAVIS_BUILD_DIR}/resources/media
  - export STATIC_DIRECTORY=${TRAVIS_BUILD_DIR}/resources/static
  - export CERTBOT_DIRECTORY=${TRAVIS_BUILD_DIR}/resources/certbot

  # Production-related environment, shortcut `on_production`
  - export SSHPASS=${PRODUCTION_SERVER_PASSWORD}
  - alias on_production='sshpass -e ssh ${PRODUCTION_SERVER_USERNAME}@${PRODUCTION_SERVER_HOST}'
  - shopt -s expand_aliases
  - ssh-keyscan -t rsa ${PRODUCTION_SERVER_HOST} > ~/.ssh/known_hosts
  - export PRODUCTION_DATABASE_BACKUP_PATH=/tmp/vash_database.sql
  - export PRODUCTION_USER_ID=`(on_production 'id -u')`
  - export HOST_USER_ID=${PRODUCTION_USER_ID}

  # Get Nginx image names and filename
  - export DOCKER_NGINX_IMAGE=vash_nginx:${COMMIT}

  # Get Django image name and filename
  - export DOCKER_DJANGO_IMAGE=vash_django:${COMMIT}

  # Get Postgres image name and filename
  - export docker_postgres_line=`cat .env | grep DOCKER_POSTGRES_IMAGE`
  - export DOCKER_POSTGRES_IMAGE=`echo ${docker_postgres_line/DOCKER_POSTGRES_IMAGE=/}`
  - export DOCKER_POSTGRES_IMAGE_FILENAME=`echo ${DOCKER_POSTGRES_IMAGE/:/_}.tar`

  # Download production database to migrate later
  - >
    on_production "
      echo > ${PRODUCTION_DATABASE_BACKUP_PATH}
      chown 660 ${PRODUCTION_DATABASE_BACKUP_PATH}
      docker exec vash_postgres_1 pg_dump -U vash vash > ${PRODUCTION_DATABASE_BACKUP_PATH}
    "
  - >
    sshpass \
      -e scp \
      ${PRODUCTION_SERVER_USERNAME}@${PRODUCTION_SERVER_HOST}:${PRODUCTION_DATABASE_BACKUP_PATH} \
      /tmp/vash_database.sql
  - on_production "rm -rf ${PRODUCTION_DATABASE_BACKUP_PATH}"


install:
  - sudo chown -R ${PRODUCTION_USER_ID}:travis .  # Travis and production user ids differ

  # Build and run
  - >
    docker-compose \
      -f compose/nginx.yml \
      -f compose/django.yml \
      -f compose/postgres.yml \
      -f compose/production.yml \
      --project-directory . \
      up \
      -d \
      --build

  # Wait for Postgres to get ready
  - >
    until [[ "$( docker exec vash_postgres_1 pg_isready )" ]];
    do echo 'Sleeping.'; sleep 5s; done

  # Wait for Postgres to create a database
  - >
    while [ "$( docker exec vash_postgres_1 psql -U vash -tAc "SELECT 1 FROM pg_database WHERE datname='vash'" )" != '1' ];
    do echo 'Sleeping.'; sleep 5s; done

  # Wait for Postgres to get ready again. Postgres restarts after creating a database
  - >
    until [[ "$( docker exec vash_postgres_1 pg_isready )" ]];
    do echo 'Sleeping.'; sleep 5s; done

  # Load backup and migrate
  - docker cp /tmp/vash_database.sql vash_postgres_1:/tmp
  - docker exec vash_postgres_1 bash -c "psql -U vash vash < /tmp/vash_database.sql"
  - docker exec vash_django_1 python manage.py migrate --noinput

  # Collect static
  - sudo chown -R ${PRODUCTION_USER_ID}:travis ${STATIC_DIRECTORY}
  - docker exec vash_django_1 python manage.py collectstatic --noinput


before_script:
  - mkdir /tmp/images  # Will store Docker tar images here
  - mkdir /tmp/artifacts  # Will store Django static gzipped tarballs here

  # Upload Nginx image to production
  - DOCKER_NGINX_IMAGE_DIRECTORY=/tmp/images/nginx
  - DOCKER_NGINX_IMAGE_FILENAME=${DOCKER_NGINX_IMAGE_DIRECTORY}/${COMMIT}.tar
  - mkdir ${DOCKER_NGINX_IMAGE_DIRECTORY}
  - docker save -o ${DOCKER_NGINX_IMAGE_FILENAME} ${DOCKER_NGINX_IMAGE}
  - >
    sshpass \
      -e scp \
      ${DOCKER_NGINX_IMAGE_FILENAME} \
      ${PRODUCTION_SERVER_USERNAME}@${PRODUCTION_SERVER_HOST}:~/images/vash/nginx

  # Upload Django image to production
  - DOCKER_DJANGO_IMAGE_DIRECTORY=/tmp/images/django
  - DOCKER_DJANGO_IMAGE_FILENAME=${DOCKER_DJANGO_IMAGE_DIRECTORY}/${COMMIT}.tar
  - mkdir ${DOCKER_DJANGO_IMAGE_DIRECTORY}
  - docker save -o ${DOCKER_DJANGO_IMAGE_FILENAME} ${DOCKER_DJANGO_IMAGE}
  - >
    sshpass \
      -e scp \
      ${DOCKER_DJANGO_IMAGE_FILENAME} \
      ${PRODUCTION_SERVER_USERNAME}@${PRODUCTION_SERVER_HOST}:~/images/vash/django

  # Upload Postgres image to production
  - DOCKER_POSTGRES_IMAGE_DIRECTORY=/tmp/images/postgres
  - DOCKER_POSTGRES_IMAGE_FILENAME=${DOCKER_POSTGRES_IMAGE_DIRECTORY}/${COMMIT}.tar
  - mkdir ${DOCKER_POSTGRES_IMAGE_DIRECTORY}
  - docker save -o ${DOCKER_POSTGRES_IMAGE_FILENAME} ${DOCKER_POSTGRES_IMAGE}
  - >
    sshpass \
      -e scp \
      ${DOCKER_POSTGRES_IMAGE_FILENAME} \
      ${PRODUCTION_SERVER_USERNAME}@${PRODUCTION_SERVER_HOST}:~/images/vash/postgres

  # Load images on production
  - on_production "docker load < ~/images/vash/nginx/${COMMIT}.tar"
  - on_production "docker load < ~/images/vash/django/${COMMIT}.tar"
  - on_production "docker load < ~/images/vash/postgres/${COMMIT}.tar"

  # Clone project to another place to run second compose on production
  - >
    on_production "
      cd ~/repositories/vash
      git clone https://github.com/vsevolod-skripnik/vash.git ${COMMIT}
      cd ${COMMIT}
      git checkout ${COMMIT}
      git reset --hard
    "

  # Send static to production
  - STATIC_TARBALL_FILENAME=${COMMIT}.tar.gz
  - cd ${STATIC_DIRECTORY}
  - tar -zcf /tmp/${STATIC_TARBALL_FILENAME} .
  - cd -
  - >
    sshpass \
      -e scp \
      /tmp/${STATIC_TARBALL_FILENAME} \
      ${PRODUCTION_SERVER_USERNAME}@${PRODUCTION_SERVER_HOST}:/tmp/

  - PRODUCTION_STATIC_DIRECTORY="~/artifacts/vash/static/${COMMIT}"
  - >
    on_production "
      mkdir -p ${PRODUCTION_STATIC_DIRECTORY}
      tar -zxf /tmp/${STATIC_TARBALL_FILENAME} -C ${PRODUCTION_STATIC_DIRECTORY}
    "

  # Send database to production
  - DATABASE_BACKUP_FILENAME=${COMMIT}.sql
  - docker exec vash_postgres_1 pg_dump -U vash vash > ${DATABASE_BACKUP_FILENAME}
  - on_production "mkdir -p ~/artifacts/vash/database/${COMMIT}"
  - >
    sshpass \
      -e scp \
      ${DATABASE_BACKUP_FILENAME} \
      ${PRODUCTION_SERVER_USERNAME}@${PRODUCTION_SERVER_HOST}:~/artifacts/vash/database/${COMMIT}


script:
  # Run second compose on production
  - >
    on_production "
      export DOCKER_NGINX_IMAGE=${DOCKER_NGINX_IMAGE}
      export DOCKER_DJANGO_IMAGE=${DOCKER_DJANGO_IMAGE}
      export DOCKER_POSTGRES_IMAGE=${DOCKER_POSTGRES_IMAGE}

      export HOST_USER_ID=${PRODUCTION_USER_ID}
      export DJANGO_SECRET_KEY=\"${DJANGO_SECRET_KEY}\"
      export DJANGO_DEBUG=False

      export MEDIA_DIRECTORY=~/resources/vash/media
      export CERTBOT_DIRECTORY=~/resources/vash/certbot
      export ROOT_DIRECTORY=~/repositories/vash/${COMMIT}
      export STATIC_DIRECTORY=${PRODUCTION_STATIC_DIRECTORY}

      export NGINX_HOST_HTTP_PORT=10080
      export NGINX_HOST_HTTPS_PORT=10443

      cd ~/repositories/vash/${COMMIT}
      docker-compose \
        -f compose/nginx.yml \
        -f compose/django.yml \
        -f compose/postgres.yml \
        -f compose/production.yml \
        --project-directory . \
        up \
        -d
      sudo bash /root/scripts/change_20k_to_10k.sh
    "
