language: bash

before_install:
  - export PARENT_DIRECTORY=/home/travis/build/vsevolod-skripnik
  - export ROOT_DIRECTORY=${TRAVIS_BUILD_DIR}
  - export MEDIA_DIRECTORY=${TRAVIS_BUILD_DIR}/resources/media
  - export STATIC_DIRECTORY=${TRAVIS_BUILD_DIR}/resources/static
  - export CERTBOT_DIRECTORY=${TRAVIS_BUILD_DIR}/resources/certbot

  - export SSHPASS=${PRODUCTION_SERVER_PASSWORD}
  - alias on_production='sshpass -e ssh ${PRODUCTION_SERVER_USERNAME}@${PRODUCTION_SERVER_HOST}'
  - shopt -s expand_aliases
  - ssh-keyscan -t rsa ${PRODUCTION_SERVER_HOST} > ~/.ssh/known_hosts
  - export PRODUCTION_USER_ID=`(on_production 'id -u')`

  - export DOCKER_DJANGO_IMAGE=vash_django:${TRAVIS_COMMIT}
  - export DOCKER_DJANGO_IMAGE_FILENAME=`echo "${DOCKER_DJANGO_IMAGE/:/_}"`
  - >
    HOST_USER_ID=${PRODUCTION_USER_ID} \
      docker-compose \
        -f compose/postgres.yml \
        -f compose/django.yml \
        --project-directory . \
        build
  - docker save -o ${DOCKER_DJANGO_IMAGE_FILENAME} ${DOCKER_DJANGO_IMAGE}
  - docker ps -a
  - docker images -a
  # - >
  #   sshpass \
  #     -e scp \
  #     ${DOCKER_DJANGO_IMAGE_FILENAME} \
  #     ${PRODUCTION_SERVER_USERNAME}@${PRODUCTION_SERVER_HOST}:~/images
  #
  # - on_production "docker load < ~/images/${DOCKER_DJANGO_IMAGE_FILENAME}"


addons:
  apt:
    packages:
    - sshpass
