language: bash


# Prepare environment and dependencies
before_install:
  - export HOST_USER_ID=`id -g`
  - export PARENT_DIRECTORY=/home/travis/build/vsevolod-skripnik
  - export ROOT_DIRECTORY=${TRAVIS_BUILD_DIR}
  - export MEDIA_DIRECTORY=${TRAVIS_BUILD_DIR}/resources/media
  - export STATIC_DIRECTORY=${TRAVIS_BUILD_DIR}/resources/static
  - export CERTBOT_DIRECTORY=${TRAVIS_BUILD_DIR}/resources/certbot

  - export SSHPASS=${PRODUCTION_SERVER_PASSWORD}
  - alias ssh_to_production='sshpass -e ssh ${PRODUCTION_SERVER_USERNAME}@${PRODUCTION_SERVER_HOST}'
  - shopt -s expand_aliases

# Build
install:
  - >
    docker-compose \
      -f compose/postgres.yml \
      -f compose/django.yml \
      --project-directory . \
      build

# Test
before_script:
  - echo 'Testing goes here'

# Deploy to production
script:
  - docker save -o vash_django.tar vash_django
  # and db
  - whoami

# Check if alive
after_script:
  - whoami


addons:
  apt:
    packages:
    - sshpass
