# Generated by Django 2.1.7 on 2019-04-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
        migrations.AddField(
            model_name='template',
            name='content',
            field=models.TextField(default=1, verbose_name='Content'),
            preserve_default=False,
        ),
    ]
