# Generated by Django 2.1.7 on 2019-04-30 13:21

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('template', '0002_auto_20190430_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='content',
        ),
        migrations.AddField(
            model_name='template',
            name='file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_template', to='filer.File', verbose_name='File'),
        ),
    ]
