# Generated by Django 2.1.7 on 2019-04-30 14:37

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_auto_20190430_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(default='test', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='file',
            field=filer.fields.file.FilerFileField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='file_template', to='filer.File', verbose_name='File'),
            preserve_default=False,
        ),
    ]
