# Generated by Django 2.1.7 on 2019-04-30 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_auto_20190430_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site'),
        ),
    ]
