# Generated by Django 2.1.7 on 2019-05-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0005_template_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='site',
        ),
    ]
