# Generated by Django 2.1.7 on 2019-06-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='title',
        ),
        migrations.AddField(
            model_name='snippet',
            name='name',
            field=models.CharField(default='navbar', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='slug',
            field=models.CharField(default='samurai', max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
