# Generated by Django 2.1.7 on 2019-06-04 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0028_auto_20190604_1856'),
        ('snippet', '0002_auto_20190602_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.Page', verbose_name='Page'),
        ),
    ]
