# Generated by Django 2.1.7 on 2019-06-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0003_snippet_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.CharField(max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='snippet',
            unique_together={('name', 'slug')},
        ),
    ]
