version: '3.4'

services:
  django:
    volumes:
      - ${MEDIA_DIRECTORY}/:/resources/media/
      - ${STATIC_DIRECTORY}/:/resources/static/
    command: sleep 1d
    # command: gunicorn vash.wsgi --reload -b :8000 --error-logfile - --access-logfile - -w ${GUNICORN_WORKERS_NUMBER}
