# Generated by Django 2.1.7 on 2019-04-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_page_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='related_pages',
            field=models.ManyToManyField(to='page.Page', verbose_name='Related pages'),
        ),
    ]
