# Generated by Django 2.1.7 on 2019-05-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_page_related_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='related_pages',
            field=models.ManyToManyField(blank=True, to='page.Page', verbose_name='Related pages'),
        ),
    ]
