# Generated by Django 2.1.7 on 2019-05-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20190504_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Сontent'),
        ),
    ]
