# Generated by Django 2.1.7 on 2019-05-10 10:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True, verbose_name='Meta'),
        ),
    ]
