# Generated by Django 2.1.7 on 2019-05-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_page_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Separate by comma and space', max_length=255, null=True, verbose_name='SEO keywords'),
        ),
    ]
