# Generated by Django 2.1.7 on 2019-05-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20190510_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_clean',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Clean content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(default='42', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
