# Generated by Django 2.1.7 on 2019-05-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20190510_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content_clean',
            new_name='clean_content',
        ),
    ]
