# Generated by Django 2.1.7 on 2019-05-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20190510_1647'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='page',
            name='site',
        ),
    ]
