# Generated by Django 2.1.7 on 2019-05-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_auto_20190510_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='clean_meta',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Clean meta'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(verbose_name='Created at'),
        ),
    ]
