# Generated by Django 2.1.7 on 2019-05-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_auto_20190512_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='related_pages',
        ),
        migrations.AddField(
            model_name='page',
            name='cache_url',
            field=models.TextField(blank=True, null=True, verbose_name='Cache URL'),
        ),
    ]
