# Generated by Django 2.1.7 on 2019-05-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_page_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='url',
            new_name='link',
        ),
    ]
