# Generated by Django 2.1.7 on 2019-05-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_auto_20190512_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='cache_url',
            new_name='cache_link',
        ),
    ]
