# Generated by Django 2.1.7 on 2019-05-14 08:27

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('page', '0016_auto_20190512_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='open_graph_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opengraph_image_article', to=settings.FILER_IMAGE_MODEL, verbose_name='Open Graph image'),
        ),
    ]
