# Generated by Django 2.1.7 on 2019-05-14 08:55

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import vash.utils.imagefield


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_page_open_graph_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='open_graph_image',
            field=vash.utils.imagefield.PatchedFilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='open_graph_image_article', to=settings.FILER_IMAGE_MODEL, verbose_name='Open Graph image'),
        ),
    ]
