# Generated by Django 2.1.7 on 2019-06-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
        ('page', '0018_auto_20190514_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='snippets',
            field=models.ManyToManyField(to='snippet.Snippet', verbose_name='Snippets'),
        ),
    ]
