# Generated by Django 2.1.7 on 2019-06-02 14:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_page_clean_snippets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='clean_snippets',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True, verbose_name='Clean snippets'),
        ),
    ]
