# Generated by Django 2.1.7 on 2019-06-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0021_auto_20190602_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='snippets',
            field=models.ManyToManyField(blank=True, null=True, to='snippet.Snippet', verbose_name='Snippets'),
        ),
    ]
