# Generated by Django 2.1.7 on 2019-06-02 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
        ('page', '0023_auto_20190602_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAndSnippetRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Page', verbose_name='Page')),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippet.Snippet', verbose_name='Snippet')),
            ],
        ),
    ]
