# Generated by Django 2.1.7 on 2019-06-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0025_remove_page_snippets'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageandsnippetrelation',
            name='name',
            field=models.CharField(default='navbar', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
