# Generated by Django 2.1.7 on 2019-06-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0002_auto_20190602_1528'),
        ('page', '0026_pageandsnippetrelation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageandsnippetrelation',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pageandsnippetrelation',
            name='snippet',
        ),
        migrations.AddField(
            model_name='page',
            name='snippets',
            field=models.ManyToManyField(blank=True, to='snippet.Snippet', verbose_name='Snippets'),
        ),
        migrations.DeleteModel(
            name='PageAndSnippetRelation',
        ),
    ]
