# Generated by Django 2.1.7 on 2019-06-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0029_auto_20190605_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='clean_content',
        ),
    ]
