# Generated by Django 2.1.7 on 2019-06-05 13:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0030_remove_page_clean_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='clean_snippets',
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True, verbose_name='Content'),
        ),
    ]
