# Generated by Django 2.1.7 on 2019-06-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0031_auto_20190605_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='link',
            new_name='detail_link',
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
